# public address to listen on
address: 127.0.0.1:12000

# URL for specific binary
binary.gateway.minimum.url: ""

# peer version
binary.gateway.minimum.version: v0.0.1

# percentage of nodes which should roll-out to the suggested version
binary.gateway.rollout.cursor: 0

# prior configuration's cursor value. if 100%, will be capped at the current cursor.
binary.gateway.rollout.previous-cursor: 100

# random 32 byte, hex-encoded string
binary.gateway.rollout.seed: "0000000000000000000000000000000000000000000000000000000000000001"

# URL for specific binary
binary.gateway.suggested.url: ""

# peer version
binary.gateway.suggested.version: v0.0.1

# URL for specific binary
binary.identity.minimum.url: ""

# peer version
binary.identity.minimum.version: v0.0.1

# percentage of nodes which should roll-out to the suggested version
binary.identity.rollout.cursor: 0

# prior configuration's cursor value. if 100%, will be capped at the current cursor.
binary.identity.rollout.previous-cursor: 100

# random 32 byte, hex-encoded string
binary.identity.rollout.seed: "0000000000000000000000000000000000000000000000000000000000000001"

# URL for specific binary
binary.identity.suggested.url: ""

# peer version
binary.identity.suggested.version: v0.0.1

# URL for specific binary
binary.satellite.minimum.url: ""

# peer version
binary.satellite.minimum.version: v0.0.1

# percentage of nodes which should roll-out to the suggested version
binary.satellite.rollout.cursor: 0

# prior configuration's cursor value. if 100%, will be capped at the current cursor.
binary.satellite.rollout.previous-cursor: 100

# random 32 byte, hex-encoded string
binary.satellite.rollout.seed: "0000000000000000000000000000000000000000000000000000000000000001"

# URL for specific binary
binary.satellite.suggested.url: ""

# peer version
binary.satellite.suggested.version: v0.0.1

# URL for specific binary
binary.storagenode-updater.minimum.url: ""

# peer version
binary.storagenode-updater.minimum.version: v0.0.1

# percentage of nodes which should roll-out to the suggested version
binary.storagenode-updater.rollout.cursor: 0

# prior configuration's cursor value. if 100%, will be capped at the current cursor.
binary.storagenode-updater.rollout.previous-cursor: 100

# random 32 byte, hex-encoded string
binary.storagenode-updater.rollout.seed: "0000000000000000000000000000000000000000000000000000000000000001"

# URL for specific binary
binary.storagenode-updater.suggested.url: ""

# peer version
binary.storagenode-updater.suggested.version: v0.0.1

# URL for specific binary
binary.storagenode.minimum.url: ""

# peer version
binary.storagenode.minimum.version: v0.0.1

# percentage of nodes which should roll-out to the suggested version
binary.storagenode.rollout.cursor: 0

# prior configuration's cursor value. if 100%, will be capped at the current cursor.
binary.storagenode.rollout.previous-cursor: 100

# random 32 byte, hex-encoded string
binary.storagenode.rollout.seed: "0000000000000000000000000000000000000000000000000000000000000001"

# URL for specific binary
binary.storagenode.suggested.url: ""

# peer version
binary.storagenode.suggested.version: v0.0.1

# URL for specific binary
binary.uplink.minimum.url: ""

# peer version
binary.uplink.minimum.version: v0.0.1

# percentage of nodes which should roll-out to the suggested version
binary.uplink.rollout.cursor: 0

# prior configuration's cursor value. if 100%, will be capped at the current cursor.
binary.uplink.rollout.previous-cursor: 100

# random 32 byte, hex-encoded string
binary.uplink.rollout.seed: "0000000000000000000000000000000000000000000000000000000000000001"

# URL for specific binary
binary.uplink.suggested.url: ""

# peer version
binary.uplink.suggested.version: v0.0.1

# address to listen on for debug endpoints
debug.addr: 127.0.0.1:12009

# If set, a path to write a process trace SVG to
# debug.trace-out: ""

# if true, log function filename and line number
# log.caller: true

# if true, set logging to development mode
# log.development: true

# configures log encoding. can either be 'console', 'json', 'pretty', or 'gcloudlogging'.
# log.encoding: ""

# the minimum log level to log
# log.level: debug

# can be stdout, stderr, or a filename
# log.output: stderr

# if true, log stack traces
# log.stack: true

# address(es) to send telemetry to (comma-separated)
# metrics.addr: ""

# application name for telemetry identification. Ignored for certain applications.
# metrics.app: versioncontrol

# application suffix. Ignored for certain applications.
metrics.app-suffix: sim

# address(es) to send telemetry to (comma-separated)
# metrics.event-addr: ""

# instance id prefix
# metrics.instance-prefix: ""

# how frequently to send up telemetry. Ignored for certain applications.
# metrics.interval: 1m0s

# how long to go between recalculating the current cursors. 0 means on demand.
regen-interval: 5m0s

# the safe daily fractional increase for a rollout (a value of .5 means 0 to 50% in 24 hours). 0 means immediate rollout.
safe-rate: 0.2

# address for jaeger agent
# tracing.agent-addr: 127.0.0.1:5775

# application name for tracing identification
# tracing.app: versioncontrol

# application suffix
# tracing.app-suffix: -dev

# buffer size for collector batch packet size
# tracing.buffer-size: 0

# whether tracing collector is enabled
# tracing.enabled: true

# how frequently to flush traces to tracing agent
# tracing.interval: 0s

# buffer size for collector queue size
# tracing.queue-size: 0

# how frequent to sample traces
# tracing.sample: 0

# Allowed Gateway Versions
versions.gateway: v0.0.1

# Allowed Identity Versions
versions.identity: v0.0.1

# Allowed Satellite Versions
versions.satellite: v0.0.1

# Allowed Storagenode Versions
versions.storagenode: v0.0.1

# Allowed Uplink Versions
versions.uplink: v0.0.1
