# server address of the api gateway and frontend app
console.address: 127.0.0.1:15002

# path to static resources
console.static-dir: /Users/sunamoto/Documents/program/storj/web/multinode

# multinode database connection string
# database: sqlite3://file:/Users/sunamoto/Library/Application Support/Storj/Local-Network/multinode/0/master.db

# Maximum Database Connection Lifetime, -1ns means the stdlib default
# db.conn_max_lifetime: 30m0s

# Maximum Amount of Idle Database connections, -1 means the stdlib default
# db.max_idle_conns: 1

# Maximum Amount of Open Database connections, -1 means the stdlib default
# db.max_open_conns: 5

# address to listen on for debug endpoints
debug.addr: 127.0.0.1:15009

# If set, a path to write a process trace SVG to
# debug.trace-out: ""

# path to the certificate chain for this identity
identity.cert-path: ./identity.cert

# path to the private key for this identity
identity.key-path: ./identity.key

# if true, log function filename and line number
# log.caller: true

# if true, set logging to development mode
# log.development: true

# configures log encoding. can either be 'console', 'json', 'pretty', or 'gcloudlogging'.
# log.encoding: ""

# the minimum log level to log
# log.level: debug

# can be stdout, stderr, or a filename
# log.output: stderr

# if true, log stack traces
# log.stack: true

# address(es) to send telemetry to (comma-separated)
# metrics.addr: ""

# application name for telemetry identification. Ignored for certain applications.
# metrics.app: multinode

# application suffix. Ignored for certain applications.
metrics.app-suffix: sim

# address(es) to send telemetry to (comma-separated)
# metrics.event-addr: ""

# instance id prefix
# metrics.instance-prefix: ""

# how frequently to send up telemetry. Ignored for certain applications.
# metrics.interval: 1m0s

# address for jaeger agent
# tracing.agent-addr: 127.0.0.1:5775

# application name for tracing identification
# tracing.app: multinode

# application suffix
# tracing.app-suffix: -dev

# buffer size for collector batch packet size
# tracing.buffer-size: 0

# whether tracing collector is enabled
# tracing.enabled: true

# how frequently to flush traces to tracing agent
# tracing.interval: 0s

# buffer size for collector queue size
# tracing.queue-size: 0

# how frequent to sample traces
# tracing.sample: 0
