access: 18HGwKTbE435sC5YJWDNrrN8Kv66yqwiCw3Sv5ovmvLLcKtbnp2QA3o3Zw6yovr6JVESnWR1mVHRUu95kKtpobLN8GsnALrJLp7zsDTaWNchPwHhp61VUqk9z51jGWnq4qqVJz6z2rwcR1RbPrjc7KGRPqx1MgoNwNQVj7iRnEBXkU9UxeNLTVATYeLzk32ARK7p7YiBEC14q7a3MCt1FZXw7N4ncJFzWWMTEV3Kzkr78pwUJAjLBMzzsJZD
debug:
  addr: 127.0.0.1:11009
metrics:
  app-suffix: sim
minio:
  access-key: a2qTtmWAmeVBn2tdUbsTy1hH3Gz
  secret-key: LDZDE4p28hEPWJx9jVEJ2rMaEFq
server:
  address: 127.0.0.1:11000
